# https://taskfile.dev

version: "3"

env:
  TEMP_DIR: .cache/.task

tasks:
  server:
    cmd: hugo server -D
        

  default:
    sources:
    - "./**/readme.md"
    -  ./scripts/readme_to_index
    -  ./scripts/update_config_with_menu
    method: timestamp 
    cmds:
    - ./scripts/readme_to_index
    - ./scripts/update_config_with_menu
    generates:
    - "./**/_index.md"

  install: brew install hugo
  version: hugo version
  publish: hugo
