# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
    # - task: sass
    - task: mark
    - task: hugo

  hugo:
    sources:
    - ".hugo/layouts/**/*.html"
    - ".hugo/assets/**/*.js"
    method: timestamp
    cmd: ./hugo server --disableFastRender --watch=0

  mark:
    sources:
    - "./**/readme.ipynb"
    - "./**/readme.md"
    - "base.config.yaml"
    method: timestamp
    cmds:
    - ./.hugo/scripts/ipynb_to_markdown --all
    - ./.hugo/scripts/readme_to_index
    - ./.hugo/scripts/update_config_with_menu

  sass:
    sources:
    - ".hugo/assets/**/*.scss"
    method: timestamp
    cmd: sass --no-source-map .hugo/assets/scss/site.scss .hugo/assets/css/main.css

  commit:
    cmds:
    - git add . -A
    - git commit --amend --no-edit
    - git push --force
