version: "3"

services:

  zookeeper: &zookeeper
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: "1"


  kafka0:
    image: confluentinc/cp-kafka:6.2.0
    ports: [ "9090:9090"]
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXT://:9090,INT://:19092,
      KAFKA_ADVERTISED_LISTENERS: EXT://localhost:9090,INT://kafka0:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXT:PLAINTEXT,INT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
    depends_on:
    - "zookeeper"
    volumes:
      - ./data/kafka0:/var/lib/kafka

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    ports: [ "9091:9091"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXT://:9091,INT://:29092,
      KAFKA_ADVERTISED_LISTENERS: EXT://localhost:9091,INT://kafka1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXT:PLAINTEXT,INT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
    depends_on:
    - "zookeeper"
    volumes:
      - ./data/kafka1:/var/lib/kafka

  kafka2:
    image: confluentinc/cp-kafka:6.2.0
    ports: [ "9092:9092"]
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXT://:9092,INT://:39092,
      KAFKA_ADVERTISED_LISTENERS: EXT://localhost:9092,INT://kafka2:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXT:PLAINTEXT,INT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
    depends_on:
    - "zookeeper"
    volumes:
      - ./data/kafka3:/var/lib/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka0
      - kafka1
      - kafka2
    ports:
      - 9001:9000
    environment:
      KAFKA_BROKERCONNECT: kafka0:19092


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
    - 9000:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:19092
    depends_on:
    - kafka0
    - kafka1
    - kafka2
