version: '3.7'

services:

  postgresql:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./_tmp_northwind2.sql:/docker-entrypoint-initdb.d/northwind.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: northwind
    restart: "on-failure"



volumes:
  postgres: {}
