// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package clientstreaming_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	Avg(ctx context.Context, opts ...grpc.CallOption) (Calculator_AvgClient, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Avg(ctx context.Context, opts ...grpc.CallOption) (Calculator_AvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[0], "/ua.made.clientstreaming.Calculator/Avg", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorAvgClient{stream}
	return x, nil
}

type Calculator_AvgClient interface {
	Send(*wrapperspb.UInt64Value) error
	CloseAndRecv() (*wrapperspb.DoubleValue, error)
	grpc.ClientStream
}

type calculatorAvgClient struct {
	grpc.ClientStream
}

func (x *calculatorAvgClient) Send(m *wrapperspb.UInt64Value) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorAvgClient) CloseAndRecv() (*wrapperspb.DoubleValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrapperspb.DoubleValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility
type CalculatorServer interface {
	Avg(Calculator_AvgServer) error
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (UnimplementedCalculatorServer) Avg(Calculator_AvgServer) error {
	return status.Errorf(codes.Unimplemented, "method Avg not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Avg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).Avg(&calculatorAvgServer{stream})
}

type Calculator_AvgServer interface {
	SendAndClose(*wrapperspb.DoubleValue) error
	Recv() (*wrapperspb.UInt64Value, error)
	grpc.ServerStream
}

type calculatorAvgServer struct {
	grpc.ServerStream
}

func (x *calculatorAvgServer) SendAndClose(m *wrapperspb.DoubleValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorAvgServer) Recv() (*wrapperspb.UInt64Value, error) {
	m := new(wrapperspb.UInt64Value)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ua.made.clientstreaming.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Avg",
			Handler:       _Calculator_Avg_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "client-streaming/proto/clientstreaming.proto",
}
