/*! comment should match `Code generated .* DO NOT EDIT.` regexp */
// This file was automatically generated by Quasilyte.

package testdata_gocritic

// Example for the rule: codegenComment

func _(s string) []byte {
	var b []byte
	copy(b, []byte(s))
	return b
}
