// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: example/example.proto

package example

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Colors int32

const (
	Colors_NONE    Colors = 0
	Colors_RED     Colors = 1
	Colors_CRIMSON Colors = 1
	Colors_GREEN   Colors = 2
	Colors_YELLOW  Colors = 3
)

// Enum value maps for Colors.
var (
	Colors_name = map[int32]string{
		0: "NONE",
		1: "RED",
		// Duplicate value: 1: "CRIMSON",
		2: "GREEN",
		3: "YELLOW",
	}
	Colors_value = map[string]int32{
		"NONE":    0,
		"RED":     1,
		"CRIMSON": 1,
		"GREEN":   2,
		"YELLOW":  3,
	}
)

func (x Colors) Enum() *Colors {
	p := new(Colors)
	*p = x
	return p
}

func (x Colors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Colors) Descriptor() protoreflect.EnumDescriptor {
	return file_example_example_proto_enumTypes[0].Descriptor()
}

func (Colors) Type() protoreflect.EnumType {
	return &file_example_example_proto_enumTypes[0]
}

func (x Colors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Colors.Descriptor instead.
func (Colors) EnumDescriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0}
}

// Nested Enum Type
type Example_Shape int32

const (
	Example_NONE     Example_Shape = 0
	Example_CUBE     Example_Shape = 1
	Example_CIRCLE   Example_Shape = 2
	Example_TRIANGLE Example_Shape = 3
)

// Enum value maps for Example_Shape.
var (
	Example_Shape_name = map[int32]string{
		0: "NONE",
		1: "CUBE",
		2: "CIRCLE",
		3: "TRIANGLE",
	}
	Example_Shape_value = map[string]int32{
		"NONE":     0,
		"CUBE":     1,
		"CIRCLE":   2,
		"TRIANGLE": 3,
	}
)

func (x Example_Shape) Enum() *Example_Shape {
	p := new(Example_Shape)
	*p = x
	return p
}

func (x Example_Shape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Example_Shape) Descriptor() protoreflect.EnumDescriptor {
	return file_example_example_proto_enumTypes[1].Descriptor()
}

func (Example_Shape) Type() protoreflect.EnumType {
	return &file_example_example_proto_enumTypes[1]
}

func (x Example_Shape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Example_Shape.Descriptor instead.
func (Example_Shape) EnumDescriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0, 0}
}

type Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Example_Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// repeated stands for slice
	Color Colors           `protobuf:"varint,2,opt,name=color,proto3,enum=Colors" json:"color,omitempty"`
	Shape Example_Shape    `protobuf:"varint,3,opt,name=shape,proto3,enum=Example_Shape" json:"shape,omitempty"`
	Other *Main_Derivative `protobuf:"bytes,6,opt,name=other,proto3" json:"other,omitempty"`
	// Types that are assignable to Oneof:
	//	*Example_Header
	//	*Example_Subheader
	Oneof        isExample_Oneof   `protobuf_oneof:"oneof"`
	Localization map[string]string `protobuf:"bytes,10,rep,name=localization,proto3" json:"localization,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ReqString    string            `protobuf:"bytes,11,opt,name=req_string,json=reqString,proto3" json:"req_string,omitempty"`
	OptString    *string           `protobuf:"bytes,12,opt,name=opt_string,json=optString,proto3,oneof" json:"opt_string,omitempty"`
}

func (x *Example) Reset() {
	*x = Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetMessages() []*Example_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Example) GetColor() Colors {
	if x != nil {
		return x.Color
	}
	return Colors_NONE
}

func (x *Example) GetShape() Example_Shape {
	if x != nil {
		return x.Shape
	}
	return Example_NONE
}

func (x *Example) GetOther() *Main_Derivative {
	if x != nil {
		return x.Other
	}
	return nil
}

func (m *Example) GetOneof() isExample_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (x *Example) GetHeader() string {
	if x, ok := x.GetOneof().(*Example_Header); ok {
		return x.Header
	}
	return ""
}

func (x *Example) GetSubheader() string {
	if x, ok := x.GetOneof().(*Example_Subheader); ok {
		return x.Subheader
	}
	return ""
}

func (x *Example) GetLocalization() map[string]string {
	if x != nil {
		return x.Localization
	}
	return nil
}

func (x *Example) GetReqString() string {
	if x != nil {
		return x.ReqString
	}
	return ""
}

func (x *Example) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

type isExample_Oneof interface {
	isExample_Oneof()
}

type Example_Header struct {
	Header string `protobuf:"bytes,8,opt,name=header,proto3,oneof"`
}

type Example_Subheader struct {
	Subheader string `protobuf:"bytes,9,opt,name=subheader,proto3,oneof"`
}

func (*Example_Header) isExample_Oneof() {}

func (*Example_Subheader) isExample_Oneof() {}

type Main struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Main) Reset() {
	*x = Main{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main) ProtoMessage() {}

func (x *Main) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main.ProtoReflect.Descriptor instead.
func (*Main) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{1}
}

// Nested Message
type Example_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Example_Message) Reset() {
	*x = Example_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Message) ProtoMessage() {}

func (x *Example_Message) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Message.ProtoReflect.Descriptor instead.
func (*Example_Message) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Example_Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Main_Derivative struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Main_Derivative) Reset() {
	*x = Main_Derivative{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Main_Derivative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Main_Derivative) ProtoMessage() {}

func (x *Main_Derivative) ProtoReflect() protoreflect.Message {
	mi := &file_example_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Main_Derivative.ProtoReflect.Descriptor instead.
func (*Main_Derivative) Descriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Main_Derivative) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_example_example_proto protoreflect.FileDescriptor

var file_example_example_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb0, 0x04, 0x0a, 0x07, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x2c,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x05,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x73, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x73,
	0x68, 0x61, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x05, 0x73, 0x68, 0x61, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x72, 0x69, 0x76, 0x61, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x45, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0a, 0x6f, 0x70, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x1a, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x3f, 0x0a, 0x11, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x55, 0x42,
	0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x49, 0x52, 0x43, 0x4c, 0x45, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x54, 0x52, 0x49, 0x41, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x03, 0x42, 0x07, 0x0a,
	0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6f, 0x70, 0x74, 0x5f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x06, 0x4a, 0x04, 0x08, 0x0f, 0x10,
	0x10, 0x4a, 0x08, 0x08, 0x63, 0x10, 0x80, 0x80, 0x80, 0x80, 0x02, 0x52, 0x03, 0x66, 0x6f, 0x6f,
	0x52, 0x03, 0x62, 0x61, 0x72, 0x22, 0x2a, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0x1a, 0x22, 0x0a,
	0x0a, 0x44, 0x65, 0x72, 0x69, 0x76, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2a, 0x43, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x52, 0x49, 0x4d, 0x53, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47,
	0x52, 0x45, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x59, 0x45, 0x4c, 0x4c, 0x4f, 0x57,
	0x10, 0x03, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_example_proto_rawDescOnce sync.Once
	file_example_example_proto_rawDescData = file_example_example_proto_rawDesc
)

func file_example_example_proto_rawDescGZIP() []byte {
	file_example_example_proto_rawDescOnce.Do(func() {
		file_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_example_proto_rawDescData)
	})
	return file_example_example_proto_rawDescData
}

var file_example_example_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_example_example_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_example_proto_goTypes = []interface{}{
	(Colors)(0),             // 0: Colors
	(Example_Shape)(0),      // 1: Example.Shape
	(*Example)(nil),         // 2: Example
	(*Main)(nil),            // 3: Main
	(*Example_Message)(nil), // 4: Example.Message
	nil,                     // 5: Example.LocalizationEntry
	(*Main_Derivative)(nil), // 6: Main.Derivative
}
var file_example_example_proto_depIdxs = []int32{
	4, // 0: Example.messages:type_name -> Example.Message
	0, // 1: Example.color:type_name -> Colors
	1, // 2: Example.shape:type_name -> Example.Shape
	6, // 3: Example.other:type_name -> Main.Derivative
	5, // 4: Example.localization:type_name -> Example.LocalizationEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_example_example_proto_init() }
func file_example_example_proto_init() {
	if File_example_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Main_Derivative); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_example_example_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Example_Header)(nil),
		(*Example_Subheader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_example_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_example_proto_goTypes,
		DependencyIndexes: file_example_example_proto_depIdxs,
		EnumInfos:         file_example_example_proto_enumTypes,
		MessageInfos:      file_example_example_proto_msgTypes,
	}.Build()
	File_example_example_proto = out.File
	file_example_example_proto_rawDesc = nil
	file_example_example_proto_goTypes = nil
	file_example_example_proto_depIdxs = nil
}
