global:
  # how frequent to scrape targets.
  # 1s means app metrics will be scraped every 1s.
  scrape_interval: 1s

scrape_configs:
  # - job_name: 'vmagent'
  #   static_configs:
  #     - targets: ['vmagent:8429']

  - job_name: 'demo'
    static_configs:
        # HTTP address of application.
        # By default, handler '/metrics' will be called.
        # substitute 'localhost' with 'docker.for.mac.host.internal' for MacOS.
      - targets: ['demo:8080']
