// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bidirectionalstreaming_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	AvgLast10(ctx context.Context, opts ...grpc.CallOption) (Calculator_AvgLast10Client, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) AvgLast10(ctx context.Context, opts ...grpc.CallOption) (Calculator_AvgLast10Client, error) {
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[0], "/ua.made.bidirectionalstreaming.Calculator/AvgLast10", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorAvgLast10Client{stream}
	return x, nil
}

type Calculator_AvgLast10Client interface {
	Send(*wrapperspb.UInt64Value) error
	Recv() (*wrapperspb.DoubleValue, error)
	grpc.ClientStream
}

type calculatorAvgLast10Client struct {
	grpc.ClientStream
}

func (x *calculatorAvgLast10Client) Send(m *wrapperspb.UInt64Value) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorAvgLast10Client) Recv() (*wrapperspb.DoubleValue, error) {
	m := new(wrapperspb.DoubleValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility
type CalculatorServer interface {
	AvgLast10(Calculator_AvgLast10Server) error
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (UnimplementedCalculatorServer) AvgLast10(Calculator_AvgLast10Server) error {
	return status.Errorf(codes.Unimplemented, "method AvgLast10 not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_AvgLast10_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).AvgLast10(&calculatorAvgLast10Server{stream})
}

type Calculator_AvgLast10Server interface {
	Send(*wrapperspb.DoubleValue) error
	Recv() (*wrapperspb.UInt64Value, error)
	grpc.ServerStream
}

type calculatorAvgLast10Server struct {
	grpc.ServerStream
}

func (x *calculatorAvgLast10Server) Send(m *wrapperspb.DoubleValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorAvgLast10Server) Recv() (*wrapperspb.UInt64Value, error) {
	m := new(wrapperspb.UInt64Value)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ua.made.bidirectionalstreaming.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AvgLast10",
			Handler:       _Calculator_AvgLast10_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bidirectional-streaming/proto/bidirectional-streaming.proto",
}
