# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    sources:
    - ./csv.sh
    - ./example_*.json
    - ./example_*.csv
    method: timestamp
    cmds:
    - clear
    # - ./install.sh
    - ./csv.sh
