# This file contains all available configuration options
# with their default values.
# options for analysis running
run:
  timeout: 15s
  issues-exit-code: 1

# Output configuration options
output:
  format: line-number
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  sort-results: true

issues:
  max-issues-per-linter: 0


linters:
  enable:
    - revive
  disable-all: true


linters-settings:
  revive:
#     # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    confidence: 0.5
    severity: warning
    rules:
      - name: add-constant
        severity: warning
        arguments:
        - maxLitCount: "3"
          allowStrs: '""'
          allowInts: "0,1,2"
          allowFloats: "0.0,0.,1.0,1.,2.0,2."

      - name: argument-limit
        severity: warning
        arguments: 3

      - name: atomic
        severity: warning

      - name: bare-return
        severity: warning

      - name: blank-imports
        severity: warning

      - name: bool-literal-in-expr
        severity: warning

      - name: call-to-gc
        severity: warning

      - name: cognitive-complexity
        severity: warning
        arguments: 2

      - name: confusing-naming
        severity: warning

      - name: confusing-results
        severity: warning

      - name: constant-logical-expr
        severity: warning

      - name: context-as-argument
        severity: warning

      - name: context-keys-type
        severity: warning

      - name: cyclomatic
        severity: warning
        arguments: 3

      - name: deep-exit
        severity: warning

      - name: defer
        severity: warning
        arguments:
        - - "call-chain"
          - "loop"
          - "recover"
          - "return"
          - "method-call"

      - name: dot-imports
        severity: warning

      - name: duplicated-imports
        severity: warning

      - name: early-return
        severity: warning

      - name: empty-block
        severity: warning

      - name: empty-lines
        severity: warning

      - name: error-naming
        severity: warning

      - name: error-return
        severity: warning

      # doesn't trigger
      - name: error-strings
        severity: warning

      - name: errorf
        severity: warning

      - name: exported
        severity: warning
        arguments:
          - "checkPrivateReceivers"
          # - "disableStutteringCheck"
          - "sayRepetitiveInsteadOfStutters"


      - name: line-length-limit
        severity: warning
        arguments: 80

      - name: file-header
        severity: warning
        arguments: "file-header-check"


      - name: flag-parameter
        severity: warning

      - name: function-length
        severity: warning
        arguments:
        - 10
        - 0

      - name: get-return
        severity: warning

      - name: function-result-limit
        severity: warning
        arguments: 2

      - name: identical-branches
        severity: warning

      - name: if-return
        severity: warning

      - name: import-shadowing
        severity: warning

      - name: imports-blacklist
        severity: warning
        arguments:
        - "crypto/md5"
        - "crypto/sha1"

      - name: indent-error-flow
        severity: warning


      - name: line-length-limit
        severity: warning
        arguments: 80

      - name: max-public-structs
        severity: warning
        arguments: 2

      - name: modifies-value-receiver
        severity: warning

      - name: modifies-parameter
        severity: warning

      - name: range-val-address
        severity: warning

      - name: range-val-in-closure
        severity: warning

      - name: nested-structs
        severity: warning

      - name: receiver-naming
        severity: warning


      - name: redefines-builtin-id
        severity: warning

      - name: string-format
        severity: warning
        arguments:
        - [ "stringFormatMethod1", "/^([^A-Z]|$)/", "must not start with a capital letter"]

      - name: string-of-int
        severity: warning

      - name: struct-tag
        severity: warning

      - name: superfluous-else
        severity: warning

      - name: time-naming
        severity: warning

      - name: unconditional-recursion
        severity: warning

      - name: unexported-naming
        severity: warning

      - name: unexported-return
        severity: warning

      - name: unhandled-error
        severity: warning
        arguments:
          - "fmt.Printf"
          - "myFunction"

      # doens't trigger
      - name: unnecessary-stmt
        severity: warning

      - name: unused-parameter
        severity: warning

      - name: package-comments
        severity: warning

      - name: increment-decrement
        severity: warning

      - name: range
        severity: warning

      - name: unreachable-code
        severity: warning

      - name: unused-receiver
        severity: warning

      - name: useless-break
        severity: warning

      - name: var-naming
        severity: warning
        arguments:
        - - "ID"
          - "VM"

      - name: var-declaration
        severity: warning

      - name: waitgroup-by-value
        severity: warning
