# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
    - hello world

  gocritic:
    sources:
    - ./testdata-gocritic/*.go
    - ./Makefile
    method: timestamp
    cmds:
    - cmd: make check-gocritic
      ignore_error: true
    - ./scripts/gocritic_golangcilint

    silent: true

  revive:
    sources:
    - ./testdata-revive/*.go
    - ./scripts/revive_checks.sh
    - ./Makefile
    method: timestamp
    cmds:
    - ./scripts/revive_updates.sh
    # - cmd: make check-revive
      # ignore_error: true
    - ./scripts/revive_checks.sh

    silent: true
